name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # chạy mỗi ngày lúc 0h UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: TinmaLai   # 👈 Username của bạn
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
